package it.uniroma2.art.semanticturkey.services.core;

import it.uniroma2.art.coda.core.CODACore;
import it.uniroma2.art.coda.exception.ConverterException;
import it.uniroma2.art.coda.exception.PRParserException;
import it.uniroma2.art.coda.provisioning.ComponentProvisioningException;
import it.uniroma2.art.coda.structures.ARTTriple;
import it.uniroma2.art.owlart.exceptions.ModelAccessException;
import it.uniroma2.art.owlart.exceptions.ModelUpdateException;
import it.uniroma2.art.owlart.exceptions.UnavailableResourceException;
import it.uniroma2.art.owlart.model.ARTNode;
import it.uniroma2.art.owlart.model.ARTResource;
import it.uniroma2.art.owlart.model.ARTURIResource;
import it.uniroma2.art.owlart.model.NodeFilters;
import it.uniroma2.art.owlart.models.ModelFactory;
import it.uniroma2.art.owlart.models.RDFModel;
import it.uniroma2.art.owlart.models.conf.ModelConfiguration;
import it.uniroma2.art.owlart.navigation.ARTNodeIterator;
import it.uniroma2.art.owlart.utilities.ModelUtilities;
import it.uniroma2.art.semanticturkey.customrange.CODACoreProvider;
import it.uniroma2.art.semanticturkey.customrange.CustomRange;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeConfig;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeConfigEntry;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeEntry;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeEntryFactory;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeEntryGraph;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeEntryNode;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeFactory;
import it.uniroma2.art.semanticturkey.customrange.CustomRangeProvider;
import it.uniroma2.art.semanticturkey.customrange.UserPromptStruct;
import it.uniroma2.art.semanticturkey.exceptions.CODAException;
import it.uniroma2.art.semanticturkey.exceptions.CustomRangeInitializationException;
import it.uniroma2.art.semanticturkey.exceptions.ProjectInconsistentException;
import it.uniroma2.art.semanticturkey.generation.annotation.GenerateSTServiceController;
import it.uniroma2.art.semanticturkey.generation.annotation.RequestMethod;
import it.uniroma2.art.semanticturkey.ontology.model.PredicateObjectsList;
import it.uniroma2.art.semanticturkey.ontology.model.PredicateObjectsListFactory;
import it.uniroma2.art.semanticturkey.ontology.utilities.RDFXMLHelp;
import it.uniroma2.art.semanticturkey.ontology.utilities.STRDFNode;
import it.uniroma2.art.semanticturkey.ontology.utilities.STRDFNodeFactory;
import it.uniroma2.art.semanticturkey.ontology.utilities.STRDFResource;
import it.uniroma2.art.semanticturkey.ontology.utilities.STRDFURI;
import it.uniroma2.art.semanticturkey.plugin.PluginManager;
import it.uniroma2.art.semanticturkey.services.STServiceAdapter;
import it.uniroma2.art.semanticturkey.services.annotations.Optional;
import it.uniroma2.art.semanticturkey.servlet.Response;
import it.uniroma2.art.semanticturkey.servlet.ServiceVocabulary.RepliesStatus;
import it.uniroma2.art.semanticturkey.servlet.XMLResponseREPLY;
import it.uniroma2.art.semanticturkey.utilities.XMLHelp;

import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;

import javax.servlet.ServletRequest;

import org.springframework.beans.factory.ObjectFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.validation.annotation.Validated;
import org.w3c.dom.Element;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.Multimap;

@GenerateSTServiceController
@Validated
@Component
public class CustomRanges extends STServiceAdapter {
	
	@Autowired
	private ObjectFactory<CODACoreProvider> codaCoreProviderFactory;
	@Autowired
	private CustomRangeProvider crProvider;
	@Autowired
	private ServletRequest request;
	
	/**
	 * This service get as parameters a custom range id and a set of userPrompt key-value pairs
	 * (userPrompt are unknown a priori, so pairs are dynamic and have to be get from the request
	 * TODO: find a better solution), then run CODA on the pearl specified in the CustomRangeEntry
	 * (with the given id <code>crEntryId</code>) and the features filled following the userPrompt parameters.
	 * Finally, "append" the triples generated by CODA to the subject-property pair
	 *  
	 * @param crEntryId
	 * @return
	 * @throws FileNotFoundException 
	 * @throws CODAException 
	 * @throws ProjectInconsistentException 
	 * @throws UnavailableResourceException 
	 * @throws ModelUpdateException 
	 * @throws CustomRangeInitializationException 
	 */
	@SuppressWarnings("unchecked")
	@GenerateSTServiceController
	public Response runCoda(ARTResource subject, ARTURIResource predicate, String crEntryId) throws FileNotFoundException, CODAException, 
			UnavailableResourceException, ProjectInconsistentException, ModelUpdateException, CustomRangeInitializationException {
		//get the parameters to put in the userPromptMap from the request
		Map<String, String[]> parMap = request.getParameterMap();//the others params (form key and values) are dynamic, get it directly from request
		Map<String, String> userPromptMap = new HashMap<String, String>();
		for (Entry<String, String[]> par : parMap.entrySet()){
//			System.out.println("param: " + par.getKey() + ", value: " + par.getValue()[0]);
			userPromptMap.put(par.getKey(), par.getValue()[0]);
		}
		//Remove useless parameters for executePearl method (parameters not belonging to userPrompt feature)
		/* N.B. if some other parameters will be put in this map, there should be no problem since
		 * when this map will be used to valorize the CAS, the value will be get based on the feature 
		 * in the TSD and the unnecessary params will be simply ignored */
		userPromptMap.remove("ctx_project");
		userPromptMap.remove("crEntryId");
		userPromptMap.remove("subject");
		userPromptMap.remove("predicate");
//		for (Entry<String, String> e : userPromptMap.entrySet()){
//			System.out.println("userPrompt: " + e.getKey() + " = " + e.getValue());
//		}
		try {
			ModelFactory<ModelConfiguration> ontFact = PluginManager.getOntManagerImpl(getProject().getOntologyManagerImplID()).createModelFactory();
			RDFModel rdfModel = getOWLModel();
			CODACore codaCore = codaCoreProviderFactory.getObject().getCODACore();
			codaCore.initialize(rdfModel, ontFact);
			CustomRangeEntry crEntry = crProvider.getCustomRangeEntryById(crEntryId);
			if (crEntry.isTypeGraph()){
				CustomRangeEntryGraph creGraph = crEntry.asCustomRangeEntryGraph();
				List<ARTTriple> triples = creGraph.executePearl(codaCore, userPromptMap);
				rdfModel.addTriple(subject, predicate, detectGraphEntry(triples), getWorkingGraph());
				for (ARTTriple triple : triples){
//					System.out.println("S:\t"+triple.getSubject()+"\nP:\t"+triple.getPredicate()+"\nO:\t"+triple.getObject());
					rdfModel.addTriple(triple.getSubject(), triple.getPredicate(), triple.getObject(), getWorkingGraph());
				}
			} else if (crEntry.isTypeNode()){
				CustomRangeEntryNode creNode = crEntry.asCustomRangeEntryNode();
				UserPromptStruct upStruct = creNode.getForm(codaCore).iterator().next();//if type=node, it's sure that there is only 1 form entry
				String value = userPromptMap.entrySet().iterator().next().getValue();//get the only value
				ARTNode artNode;
				if (upStruct.isLiteral()){
					artNode = codaCore.executeLiteralConverter(
							upStruct.getConverter(), value, upStruct.getLiteralDatatype(), upStruct.getLiteralLang());
				} else {//type "uri"
					artNode = codaCore.executeURIConverter(upStruct.getConverter(), value);
				}
//				System.out.println("S:\t"+subject.getNominalValue()+"\nP:\t"+predicate.getNominalValue()+"\nO:\t"+artNode.getNominalValue());
				rdfModel.addTriple(subject, predicate, artNode, getWorkingGraph());
			}
		} catch (PRParserException | ComponentProvisioningException | ConverterException e){
			throw new CODAException(e);
		}
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		return response;
	}
	
	/**
	 * This method detects the entry of a graph (list of triples) based on an heuristic: entry is that subject that never appears as object
	 * @param triples
	 * @return
	 */
	private ARTResource detectGraphEntry(List<ARTTriple> triples){
		for (ARTTriple t1 : triples){
			ARTResource subj = t1.getSubject();
			boolean neverObj = true;
			for (ARTTriple t2 : triples){
				if (subj.getNominalValue().equals(t2.getObject().getNominalValue()))
					neverObj = false;
			}
			if (neverObj)
				return subj;
		}
		return null;
	}
	
	/**
	 * This service returns a description of a reified resource based on the existing CustomRangeEntry
	 * of the given predicate. First it retrieves, from the pearl of the CRE, the predicates that 
	 * describe the resource, then get the values for that predicates. If no CustomRangeEntryGraph
	 * is found for the given predicate, returns an empty description.
	 * If there is no CustomRangeEntry for the given predicate, returns an empty description.
	 * 
	 * @param crEntryId
	 * @return
	 * @throws UnavailableResourceException
	 * @throws ProjectInconsistentException
	 * @throws FileNotFoundException
	 * @throws PRParserException
	 * @throws ModelAccessException 
	 * @throws CustomRangeInitializationException 
	 */
	@GenerateSTServiceController
	public Response getReifiedResourceDescription(ARTResource resource, ARTURIResource predicate) 
			throws UnavailableResourceException, ProjectInconsistentException, 
			PRParserException, ModelAccessException, CustomRangeInitializationException{
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElement = response.getDataElement();
		Element resourceElem = XMLHelp.newElement(dataElement, "resource");
		
		ModelFactory<ModelConfiguration> ontFact = PluginManager.getOntManagerImpl(getProject().getOntologyManagerImplID()).createModelFactory();
		RDFModel rdfModel = getOWLModel();
		CODACore codaCore = codaCoreProviderFactory.getObject().getCODACore();
		codaCore.initialize(rdfModel, ontFact);
		//try to identify the CRE which has generated the reified resource
		CustomRangeEntryGraph creGraph = getCREGraphSeed(resource, predicate, codaCore);
		if (creGraph != null){
			//set the show for the reified resource
			String showProp = rdfModel.expandQName(creGraph.getShowProperty());
			String show;
			if (showProp.equals("")){//if the showProperty is not specified, then show is the same resource ID (uri or bnode)
				show = resource.getNominalValue();
			} else { //if the showProperty is specified, look for its value
				ARTNodeIterator itShow = rdfModel.listValuesOfSubjPredPair(resource, rdfModel.createURIResource(showProp), false, getWorkingGraph());
				if (itShow.hasNext()){//if the value is found is set as show attribute
					ARTNode showNode = itShow.next();
					if (showNode.isLiteral())
						show = showNode.asLiteral().getLabel();
					else
						show = showNode.getNominalValue();
				} else { //otherwise set the same resource ID as show attribute
					show = resource.getNominalValue();
				}
			}
			STRDFResource stRdfRes = STRDFNodeFactory.createSTRDFResource(
					resource, ModelUtilities.getResourceRole(resource, rdfModel), true, show);
			RDFXMLHelp.addRDFResource(resourceElem, stRdfRes);
			
			//set the predicate-object list
			boolean descrAvailable = false;
			
			Map<ARTURIResource, STRDFResource> art2STRDFPredicates = new LinkedHashMap<ARTURIResource, STRDFResource>();
			Multimap<ARTURIResource, STRDFNode> resultPredicateObjectValues = HashMultimap.create();
			PredicateObjectsList predicateObjectsList = PredicateObjectsListFactory
					.createPredicateObjectsList(art2STRDFPredicates, resultPredicateObjectValues);
			
			Collection<String> predicateList = creGraph.getGraphPredicates(codaCore, false, true);
			for (String predString : predicateList){
				ARTURIResource predResource = rdfModel.createURIResource(predString);
				STRDFURI stPred = STRDFNodeFactory.createSTRDFURI(predResource, null, true, rdfModel.getQName(predString));
				
				ARTNodeIterator itValues = rdfModel.listValuesOfSubjPredPair(resource, predResource, false, getWorkingGraph());
				if (itValues.hasNext()){
					art2STRDFPredicates.put(predResource, stPred);
					descrAvailable = true;
					while (itValues.hasNext()){
						ARTNode value = itValues.next();
						STRDFNode stNode = STRDFNodeFactory.createSTRDFNode(rdfModel, value, false, true, true);
						resultPredicateObjectValues.put(predResource, stNode);
					}
				}
			}
			//is possible that there's a CRE for the given property, but the resource has no values
			//for all the predicates that describe the CRE, so add the propertiesElem to the response
			//only if at least one predicate has a value
			if (descrAvailable){
				Element propertiesElem = XMLHelp.newElement(dataElement, "properties");
				RDFXMLHelp.addPredicateObjectList(propertiesElem, predicateObjectsList);
			}
		} else {
			STRDFResource stRdfRes = STRDFNodeFactory.createSTRDFResource(
					resource, ModelUtilities.getResourceRole(resource, rdfModel), true, resource.getNominalValue());
			RDFXMLHelp.addRDFResource(resourceElem, stRdfRes);
		}
		return response;
	}
	
	/**
	 * Returns the CustomRangeEntryGraph that probably generated the reified resource.
	 * If for the given property there is no CRE available returns null,
	 * if there's just one CRE then return it, otherwise if there are multiple CRE returns the one 
	 * which its PEARL fits better the given reified resource description. 
	 * This choice in the last case is made through the following algorithm:
	 * <ul>
	 *  <li>Collect the perfect match candidates, namely the CREs which all the mandatory predicates
	 * are valued in the resource</li>
	 *  <li>If there is only one perfect candidate return that</li>
	 *  <li>If there are multiple perfect candidates, return the one with more predicates</li>
	 *   <ul>
	 *    <li>If also in this case the candidates have the same number of matched mandatory predicates,
	 *    return the one that has more total matched predicate (if multiple candidates returns the first)</li>
	 *   </ul>
	 *  <li>If there is no perfect candidate, return the one with more mandatory matched predicates</li>
	 *   <ul>
	 *    <li>If there is only one "best fit" candidate, return that</li>
	 *    <li>If there are multiple best fit candidates, return the one with more total matched
	 *    predicate (if multiple candidates, returns the first)</li>
	 *   </ul>
	 * </ul>
	 * @param resource
	 * @param predicate
	 * @return
	 * @throws UnavailableResourceException
	 * @throws ProjectInconsistentException
	 * @throws PRParserException
	 * @throws ModelAccessException
	 */
	private CustomRangeEntryGraph getCREGraphSeed(ARTResource resource, ARTURIResource predicate, CODACore codaCore) 
			throws UnavailableResourceException, ProjectInconsistentException, PRParserException, ModelAccessException{
		RDFModel rdfModel = getOWLModel();
		Collection<CustomRangeEntryGraph> crEntries = crProvider.getCustomRangeEntriesGraphForProperty(predicate.getURI());
		if (crEntries.isEmpty()){
			return null;
		} else if (crEntries.size() == 1){
			return crEntries.iterator().next();
		} else { //crEntries.size() > 1
			Collection<CREMatchingStruct> creMatchStructs = new ArrayList<CREMatchingStruct>();
			for (CustomRangeEntryGraph cre : crEntries){
				creMatchStructs.add(new CREMatchingStruct(cre, resource, rdfModel, codaCore));
			}
			//look for perfect match with only mandatory predicates
			Collection<CREMatchingStruct> perfectCandidates = new ArrayList<CREMatchingStruct>();
			for (CREMatchingStruct cremStruct : creMatchStructs){
				if (cremStruct.isPerfectMandatoryMatch())
					perfectCandidates.add(cremStruct);
			}
			if (perfectCandidates.size() == 1){//if there's only one perfect CRE candidate return it
				return perfectCandidates.iterator().next().getCustomRangeEntryGraph();
			} else if (perfectCandidates.size() > 1){//multiple perfect candidates
				//return the one with more mandatory preds
				Collection<CREMatchingStruct> biggerPerfectCandidates = new ArrayList<CREMatchingStruct>();
				int maxMandatoryPreds = 0;
				for (CREMatchingStruct cremStruct : perfectCandidates){
					if (cremStruct.getMandatoryPreds() == maxMandatoryPreds){
						biggerPerfectCandidates.add(cremStruct);
					} else if (cremStruct.getMandatoryPreds() > maxMandatoryPreds){
						maxMandatoryPreds = cremStruct.getMandatoryPreds();
						biggerPerfectCandidates.clear();
						biggerPerfectCandidates.add(cremStruct);
					}
				}
				if (biggerPerfectCandidates.size() == 1){
					return biggerPerfectCandidates.iterator().next().getCustomRangeEntryGraph();
				} else { //if there are more perfect match candidate with the same number of mandatory preds
					//return the one with more total preds match
					CREMatchingStruct bestCandidate = null;
					int maxPredsMatch = 0;
					for (CREMatchingStruct cremStruct : biggerPerfectCandidates){
						if (cremStruct.getTotalPredsMatched() > maxPredsMatch){
							maxPredsMatch = cremStruct.getTotalPredsMatched();
							bestCandidate = cremStruct;
						}
					}
					return bestCandidate.getCustomRangeEntryGraph();
				}
			} else {//perfectCandidate empty => no CRE with perfect match
				//return the CRE with more matched mandatory preds
				Collection<CREMatchingStruct> bestFitCandidates = new ArrayList<CREMatchingStruct>();
				int maxMandatoryPreds = 0;
				for (CREMatchingStruct cremStruct : creMatchStructs){
					if (cremStruct.getMandatoryPredsMatched() == maxMandatoryPreds)
						bestFitCandidates.add(cremStruct);
					else if (cremStruct.getMandatoryPredsMatched() > maxMandatoryPreds){
						bestFitCandidates.clear();
						bestFitCandidates.add(cremStruct);
					}
				}
				if (bestFitCandidates.size() == 1){
					return bestFitCandidates.iterator().next().getCustomRangeEntryGraph();
				} else { //if there are more candidate with the same number of mandatory preds matched
					//return the one with more total preds match
					CREMatchingStruct bestCandidate = null;
					int maxPredsMatch = 0;
					for (CREMatchingStruct cremStruct : bestFitCandidates){
						if (cremStruct.getTotalPredsMatched() > maxPredsMatch){
							maxPredsMatch = cremStruct.getTotalPredsMatched();
							bestCandidate = cremStruct;
						}
					}
					return bestCandidate.getCustomRangeEntryGraph();
				}
			}
		}
	}
	
	/**
	 * Private class useful to facilitate the research of a "better fit" CustomRangeEntryGraph
	 * in getCREGraphSeed
	 */
	private class CREMatchingStruct {
		private CustomRangeEntryGraph cre;
		private boolean perfectMandatoryMatch;
		private int nMandatoryPreds = 0;
		private int nMandatoryPredsMatched = 0;
		private int nTotalPredsMatched = 0;
		
		public CREMatchingStruct(CustomRangeEntryGraph creGraph, ARTResource reifRes, RDFModel model, CODACore codaCore)
				throws PRParserException, ModelAccessException{
			this.cre = creGraph;
			Collection<String> mandatoryPreds = creGraph.getGraphPredicates(codaCore, true, true);
			nMandatoryPreds = mandatoryPreds.size();
			for (String pred : mandatoryPreds){
				ARTNodeIterator itValues = model.listValuesOfSubjPredPair(reifRes, model.createURIResource(pred), false, getWorkingGraph());
				if (itValues.hasNext())
					nMandatoryPredsMatched++;
			}
			perfectMandatoryMatch = (mandatoryPreds.size() == nMandatoryPredsMatched);
			Collection<String> allPreds = creGraph.getGraphPredicates(codaCore, false, true);
			for (String pred : allPreds){
				ARTNodeIterator itValues = model.listValuesOfSubjPredPair(reifRes, model.createURIResource(pred), false, getWorkingGraph());
				if (itValues.hasNext())
					nTotalPredsMatched++;
			}
		}
		
		public CustomRangeEntryGraph getCustomRangeEntryGraph(){
			return this.cre;
		}
		public boolean isPerfectMandatoryMatch(){
			return perfectMandatoryMatch;
		}
		public int getMandatoryPreds(){
			return nMandatoryPreds;
		}
		public int getMandatoryPredsMatched(){
			return nMandatoryPredsMatched;
		}
		public int getTotalPredsMatched(){
			return nTotalPredsMatched;
		}
	}
	
	/**
	 * Removes a reified resource and all the triples where it appears as subject 
	 * @param subject
	 * @param predicate
	 * @param resource
	 * @return
	 * @throws ModelUpdateException
	 */
	@GenerateSTServiceController
	public Response removeReifiedResource(ARTURIResource subject, ARTURIResource predicate, ARTURIResource resource) throws ModelUpdateException{
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		RDFModel model = getOWLModel();
		model.deleteTriple(subject, predicate, resource, getWorkingGraph());
		model.deleteTriple(resource, NodeFilters.ANY, NodeFilters.ANY, getWorkingGraph());
		return response;
	}
	
	@GenerateSTServiceController
	public Response executeURIConverter(String converter, @Optional String value) throws ComponentProvisioningException, 
			ConverterException, UnavailableResourceException, ProjectInconsistentException {
		String result = "";
		ModelFactory<ModelConfiguration> ontFact = PluginManager.getOntManagerImpl(getProject().getOntologyManagerImplID()).createModelFactory();
		CODACore codaCore = codaCoreProviderFactory.getObject().getCODACore();
		codaCore.initialize(getOWLModel(), ontFact);
		if (value != null){
			result = codaCore.executeURIConverter(converter, value).getNominalValue();
		} else {
			result = codaCore.executeURIConverter(converter).getNominalValue();
		}
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElement = response.getDataElement();
		Element valueElement = XMLHelp.newElement(dataElement, "value");
		valueElement.setAttribute("converter", converter);
		valueElement.setTextContent(result);
		return response;
	}
	
	@GenerateSTServiceController
	public Response executeLiteralConverter(String converter, String value, @Optional String datatype, @Optional String lang) 
			throws ComponentProvisioningException, ConverterException, UnavailableResourceException, ProjectInconsistentException {
		ModelFactory<ModelConfiguration> ontFact = PluginManager.getOntManagerImpl(getProject().getOntologyManagerImplID()).createModelFactory();
		CODACore codaCore = codaCoreProviderFactory.getObject().getCODACore();
		codaCore.initialize(getOWLModel(), ontFact);
		if (datatype != null && datatype.equals(""))
			datatype = null;
		if (lang != null && lang.equals(""))
			lang = null;
		String result = codaCore.executeLiteralConverter(converter, value, datatype, lang).getNominalValue();
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElement = response.getDataElement();
		Element valueElement = XMLHelp.newElement(dataElement, "value");
		valueElement.setAttribute("converter", converter);
		valueElement.setTextContent(result);
		return response;
	}
	
	/**
	 * Returns the serialization of the CurtomRange with the given id
	 * This serialization doesn't contain the real range, it contains just the id(s) of the entries.
	 * @param id
	 * @return
	 */
	@GenerateSTServiceController
	public Response getCustomRange(String id){
		CustomRange cr = crProvider.getCustomRangeById(id);
		if (cr != null){
			XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
			Element dataElem = response.getDataElement();
			Element crElem = XMLHelp.newElement(dataElem, "customRange");
			crElem.setAttribute("id", cr.getId());
			for (String creId : cr.getEntriesId()){
				Element entryElem = XMLHelp.newElement(crElem, "entry");
				entryElem.setAttribute("id", creId);
			}
			return response;
		} else {
			return createReplyFAIL("CustomRange with id " + id + " not found");
		}
	}
	
	/**
	 * Returns all the CustomRange available
	 * @return
	 */
	@GenerateSTServiceController
	public Response getAllCustomRanges(){
		Collection<CustomRange> crColl = crProvider.getAllCustomRanges();
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElem = response.getDataElement();
		for (CustomRange cr : crColl){
			XMLHelp.newElement(dataElem, "customRange", cr.getId());
		}
		return response;
	}
	
	/**
	 * Creates an empty CustomRange (a CR without CREntries related)
	 * @param id
	 * @return
	 * @throws CustomRangeInitializationException 
	 */
	@GenerateSTServiceController
	public Response createCustomRange(String id) throws CustomRangeInitializationException{
		if (crProvider.getCustomRangeById(id) != null) {
			throw new CustomRangeInitializationException("Impossible to create a CustomRange with "
					+ "ID '" + id + "'. A CustomRange with the same ID already exists");
		}
		CustomRange cr = CustomRangeFactory.createEmptyCustomRange(id);
		cr.saveXML();
		crProvider.addCustomRange(cr);
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Deletes the CustomRange with the given id
	 * @param id
	 * @return
	 */
	@GenerateSTServiceController
	public Response deleteCustomRange(String id){
		crProvider.removeCustomRange(id);
		//remove the CustomRangeConfigEntry(es) with that CustomRange
		CustomRangeConfig crConf = crProvider.getCustomRangeConfig();
		crConf.removeConfigEntryWithCrId(id);
		crConf.saveXML();
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Returns all the CustomRangeEntry available
	 * @return
	 */
	@GenerateSTServiceController
	public Response getAllCustomRangeEntries(){
		Collection<CustomRangeEntry> creColl = crProvider.getAllCustomRangeEntries();
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElem = response.getDataElement();
		for (CustomRangeEntry cre : creColl){
			XMLHelp.newElement(dataElem, "customRangeEntry", cre.getId());
		}
		return response;
	}
	
	/**
	 * Returns the serialization of the CurtomRangeEntry with the given id
	 * @param id
	 * @return
	 */
	@GenerateSTServiceController
	public Response getCustomRangeEntry(String id){
		CustomRangeEntry crEntry = crProvider.getCustomRangeEntryById(id);
		if (crEntry != null){
			XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
			Element dataElem = response.getDataElement();
			Element creElem = XMLHelp.newElement(dataElem, "customRangeEntry");
			creElem.setAttribute("id", crEntry.getId());
			creElem.setAttribute("name", crEntry.getName());
			creElem.setAttribute("type", crEntry.getType());
			Element descriptionElem = XMLHelp.newElement(creElem, "description");
			descriptionElem.setTextContent(crEntry.getDescription());
			Element refElem = XMLHelp.newElement(creElem, "ref");
			refElem.setTextContent(crEntry.getRef());
			if (crEntry.isTypeGraph()){
				refElem.setAttribute("showProperty", crEntry.asCustomRangeEntryGraph().getShowProperty());
			}
			return response;
		} else {
			return createReplyFAIL("CustomRangeEntry with id " + id + " not found");
		}
	}
	
	/**
	 * Returns the serialization of all the CustomRangeEntry available for the given property
	 * @param property
	 * @return
	 * @throws ModelAccessException
	 */
	@GenerateSTServiceController
	public Response getCustomRangeEntries(String property) throws ModelAccessException{
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElem = response.getDataElement();
		Collection<CustomRangeEntry> crEntries = crProvider.getCustomRangeEntriesForProperty(getOWLModel().expandQName(property));
		for (CustomRangeEntry cre : crEntries){
			Element creElem = XMLHelp.newElement(dataElem, "customRangeEntry");
			creElem.setAttribute("id", cre.getId());
			creElem.setAttribute("name", cre.getName());
			creElem.setAttribute("type", cre.getType());
			Element descriptionElem = XMLHelp.newElement(creElem, "description");
			descriptionElem.setTextContent(cre.getDescription());
			Element refElem = XMLHelp.newElement(creElem, "ref");
			refElem.setTextContent(cre.getRef());
		}
		return response;
	}
	
	/**
	 * This service is thought to create a custom range entry from client.
	 * To be useful is necessary a proper UI for client support (e.g. a wizard)
	 * This is a POST because ref and description could be quite long for a GET parameter
	 * @param type
	 * @param id
	 * @param name
	 * @param description
	 * @param ref
	 * @param showProp Useful only if type is "graph"
	 * @return
	 * @throws CustomRangeInitializationException 
	 */
	@GenerateSTServiceController (method = RequestMethod.POST)
	public Response createCustomRangeEntry(String type, String id, String name, String description, String ref, @Optional String showProp)
			throws CustomRangeInitializationException {
		if (crProvider.getCustomRangeEntryById(id) != null){
			throw new CustomRangeInitializationException("Impossible to create a CustomRangeEntry with "
					+ "ID '" + id + "'. A CustomRangeEntry with the same ID already exists");
		}
		CustomRangeEntry cre = null;
		if (type.equalsIgnoreCase(CustomRangeEntry.Types.node.toString())){
			cre = CustomRangeEntryFactory.createCustomRangeEntry(CustomRangeEntry.Types.node, id, name, description, ref);
		} else {
			cre = CustomRangeEntryFactory.createCustomRangeEntry(CustomRangeEntry.Types.graph, id, name, description, ref);
			if (showProp != null && !showProp.equals(""))
				cre.asCustomRangeEntryGraph().setShowProperty(showProp);
		}
		cre.saveXML();
		crProvider.addCustomRangeEntries(cre);
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Deletes the CustomRangeEntry with the given id. Removes also the CRE on cascade from the CR
	 * that contain it. 
	 * @param id
	 * @return
	 */
	@GenerateSTServiceController
	public Response deleteCustomRangeEntry(String id){
		crProvider.removeCustomRangeEntry(id);
		//remove the entry from the CustomRange that use it
		Collection<CustomRange> crColl = crProvider.getAllCustomRanges();
		for (CustomRange cr : crColl){
			if (cr.containsEntry(id)){
				cr.removeEntry(id);
				cr.saveXML();
			}
		}
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Updates a CustomRangeEntry. Allows to change the name, the description, the ref and eventually
	 * (if the CRE is graph) the showProp of the CRE with the given id. It doesn't allow to change 
	 * the type.
	 * @param id
	 * @param name
	 * @param description
	 * @param ref
	 * @param showProp
	 * @return
	 */
	@GenerateSTServiceController (method = RequestMethod.POST)
	public Response updateCustomRangeEntry(String id, String name, String description, String ref, @Optional String showProp){
		CustomRangeEntry cre = crProvider.getCustomRangeEntryById(id);
		if (cre != null){
			cre.setName(name);
			cre.setDescription(description);
			cre.setRef(ref);
			if (showProp != null && !showProp.equals("")){
				cre.asCustomRangeEntryGraph().setShowProperty(showProp);
			}
			cre.saveXML();
			return createReplyResponse(RepliesStatus.ok);
		} else {
			return createReplyFAIL("CustomRangeEntry with id " + id + " not found");
		}
	}
	
	/**
	 * Adds an existing CustomRangeEntry to an existing CustomRange entry
	 * @param customRangeId
	 * @param customRangeEntryId
	 * @return
	 */
	@GenerateSTServiceController
	public Response addEntryToCustomRange(String customRangeId, String customRangeEntryId){
		CustomRange cr = crProvider.getCustomRangeById(customRangeId);
		CustomRangeEntry cre = crProvider.getCustomRangeEntryById(customRangeEntryId);
		if (cr == null)
			return createReplyFAIL("CustomRange with id " + customRangeId + " not found");
		if (cre == null)
			return createReplyFAIL("CustomRangeEntry with id " + customRangeEntryId + " not found");
		if (cr.addEntry(cre))
			cr.saveXML();
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Removes a CustomRangeEntry from an existing CustomRange
	 * @param customRangeId
	 * @param customRangeEntryId
	 * @return
	 */
	@GenerateSTServiceController
	public Response removeEntryFromCustomRange(String customRangeId, String customRangeEntryId){
		CustomRange cr = crProvider.getCustomRangeById(customRangeId);
		if (cr == null)
			return createReplyFAIL("CustomRange with id " + customRangeId + " not found");
		cr.removeEntry(customRangeEntryId);
		cr.saveXML();
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Returns all the property-CustomRange pairs defined in the CustomRange configuration
	 * @return
	 * @throws CustomRangeInitializationException 
	 */
	@GenerateSTServiceController
	public Response getCustomRangeConfigMap() throws CustomRangeInitializationException{
		XMLResponseREPLY response = createReplyResponse(RepliesStatus.ok);
		Element dataElem = response.getDataElement();
		Element crcElem = XMLHelp.newElement(dataElem, "customRangeConfig");
		Collection<CustomRangeConfigEntry> crConfEntries = crProvider.getCustomRangeConfig().getCustomRangeConfigEntries();
		for (CustomRangeConfigEntry crConfEntry : crConfEntries){
			Element confEntryElem = XMLHelp.newElement(crcElem, "configEntry");
			confEntryElem.setAttribute("property", crConfEntry.getProperty());
			confEntryElem.setAttribute("idCustomRange", crConfEntry.getCutomRange().getId());
			confEntryElem.setAttribute("replaceRanges", crConfEntry.getReplaceRange()+"");
		}
		return response;
	}
	
	/**
	 * Adds a CustomRange to a property 
	 * @param property
	 * @param customRangeId
	 * @param replaceRanges
	 * @return
	 */
	@GenerateSTServiceController
	public Response addCustomRangeToProperty(String customRangeId, ARTURIResource property, @Optional (defaultValue = "false") boolean replaceRanges){
		CustomRange cr = crProvider.getCustomRangeById(customRangeId);
		if (cr == null)
			return createReplyFAIL("CustomRange with id " + customRangeId + " not found");
		CustomRangeConfig crConfig = crProvider.getCustomRangeConfig();
		if (crConfig.addEntry(new CustomRangeConfigEntry(property.getURI(), cr, replaceRanges)))
				crConfig.saveXML();
		return createReplyResponse(RepliesStatus.ok);
	}
	
	/**
	 * Remove the CustomRange of the given property
	 * @param property
	 * @return
	 */
	@GenerateSTServiceController
	public Response removeCustomRangeFromProperty(ARTURIResource property){
		CustomRangeConfig crConfig = crProvider.getCustomRangeConfig();
		crConfig.removeConfigEntryFromProperty(property.getURI());
		crConfig.saveXML();
		return createReplyResponse(RepliesStatus.ok);
	}

}
